global.first_expert = [ ["I'm glad to see you carry on your father's legacy. If you need help I am here.",
						"I saw some great landscapes on my hike yesterday!",
						"Temperatures have been rising! I think there will be a drought soon!",
						"The Drought is here, I hope your water supply is enough!",
						"Glad you are safe after that one!",
						"I'm having a pleasant day with my guard dog!",
						"There is a swarm of mice coming in! If you need some repellent I have some great supplies! Its just $400!",
						"The swarm is coming!",
						"I believe your repellent was too strong, some plants died!",
						"I love grazing with my animals",
						"I've got some fertilizer for you! It's just $600",
						"Today is the day to fix your soil!",
						"I love being a shepherd, I get to meet so many interesting people like you!",
						"You did it!"
						],
						["I'm glad to see you carry on your father's legacy. If you need help I am here.",
						"I saw some great landscapes on my hike yesterday!",
						"Temperatures have been rising! I think there will be a drought soon!",
						"The Drought is here, I hope your water supply is enough!",
						"Glad you are safe after that one!",
						"I'm having a pleasant day with my guard dog!",
						"There is a swarm of mice coming in! If you need some repellent I have some great supplies! Its just $400!",
						"The swarm is coming!",
						"Looks like my repellent did the job!",
						"I love grazing with my animals",
						"I've got some fertilizer for you! It's just $600",
						"Glad I could help!",
						"I love being a shepherd, I get to meet so many interesting people like you!",
						"You did it!"
						]
]
global.second_expert = [["You have 13 days to collect evidence of crises events in your journal, to convince the government of farmer's plights",
						"I need a new smoker! My old one is too skibidi rizz!",
						"I saw an old irrigation line nearby! If you need access before the drought, it's only $50!",
						"Today is Drought Day!",
						"Unfortunately, I noticed a waterhole dried up in the drought. Many predators died and now mice are rampant!",
						"Hey there, I have some fertilizer for sale, if you would like to top off! Only $250",
						"Looks like some pests are coming in! This swarm is even worse because someone dried up the waterhole!",
						"MICE!!!!",
						"Did you get past the pests?",
						"I've got a few old mesh suits I'm replacing today, but I hope you have fun!",
						"Looks like your soil is loose and can't hold nutrition, the problem is worsened by the strong pesticides.",
						"Your choice of fertilizer was subpar, hope you can last throughout today!",
						"Being a beekeper is loads of fun!",
						"Congratulations!"
						],
						["You have 13 days to collect evidence of crises events in your journal, to convince the government of farmer's plights",
						"I need a new smoker! My old one is too skibidi rizz!",
						"I saw an old irrigation line nearby! If you need access before the drought, it's only $50!",
						"Today is Drought Day!",
						"Glad to see the old irrigation line doing you favors!",
						"Hey there, I have some fertilizer for sale, if you would like to top off! Only $250",
						"Looks like some pests are coming in! This looks manageable for you.",
						"MICE!!!!",
						"Did you get past the pests?",
						"I've got a few old mesh suits I'm replacing today, but I hope you have fun!",
						"Looks like your soil is loose and can't hold nutrition.",
						"Today is the day to fix your soil!",
						"Being a beekeper is loads of fun!",
						"Congratulations!"
						]
]
global.first_nonexpert = [ ["I am one of your father's four closest friends. I'm glad to see you have inherited his farm!",
						"How's it going! Madrid is gorgeous today.",
						"Beware of the drought! I have a water source for you, there is a watering hole not far from here. It's only $50.",
						"Brace for Drought!",
						"Maybe, the waterhole wasn't the best idea, mice are far more populous!",
						"Would you like to buy some fertilizer? Only $150",
						"A swarm of pests coming in, they seem more aggressive than usual!",
						"So many mice....",
						"Hope you are doing alright!",
						"It is fun driving a cab!",
						"Hey I have some fertilizer to solve your soil problem! It's just $600!",
						"Sorry if my fertilizer is not great, I hope I did not fail you!",
						"Your father would have been proud",
						"You gathered enough evidence and you saved the farmers"
						],
						["I am one of your father's four closest friends. I'm glad to see you have inherited his farm!",
						"How's it going! Madrid is gorgeous today.",
						"Beware of the drought! I have a water source for you, there is a watering hole not far from here. It's only $50.",
						"Brace for Drought!",
						"Good call on the waterhole, the irrigation line was far less disruptive!",
						"Would you like to buy some fertilizer? Only $150",
						"Some mice coming in, but I think you got it!",
						"So many mice....",
						"Hope you are doing alright!",
						"It is fun driving a cab!",
						"Hey I have some fertilizer to solve your soil problem! It's just $600!",
						"Sorry if my fertilizer is not great, I hope I did not fail you!",
						"Your father would have been proud",
						"You gathered enough evidence and you saved the farmers!"
						]
]
global.second_nonexpert = [ ["I'm sorry that your dad died, he gets five big booms!", 
							"My new car is beautiful!",
							"A friend told me that there will be a drought soon!",
							"AHHHHH DROUGHT!",
							"I hope your farm is doing OK after that drought!",
							"Traveling to Mallorca today, can't wait to see the beaches!",
							"While I was in Mallorca, I bought the strongest pesticide. Since there are so many mice today, you will need it. Just $500!",
							"Fend for yourself! Use my pesticide!",
							"Oops, I think my pesticide was too strong...",
							"Beautiful day to visit Barcelona",
							"Your soil's pH balance is all off. My pesticide did a real number on it.",
							"Good luck with the soil today!",
							"Owning a grovery store in Sierra Nevada is incredible!",
							"Your evidence will inspire the government to fight climate change and stop future crises!"
							],
							["I'm sorry that your dad died, he gets five big booms!", 
							"My new car is beautiful!",
							"A friend told me that there will be a drought soon!",
							"AHHHHH DROUGHT!",
							"I hope your farm is doing OK after that drought!",
							"Traveling to Mallorca today, can't wait to see the beaches!",
							"While I was in Mallorca, I bought the strongest pesticides. If this doesn't get rid of the mice, nothing will. Just $500!",
							"Fend for yourself!",
							"Thank god your pesticide worked. Mine was way too strong!",
							"Beautiful day to visit Barcelona",
							"Your soil can't hold nutrients, get some nice fertilizer!",
							"Good luck with the soil today!",
							"Owning a grovery store in Sierra Nevada is incredible!",
							"Your evidence will inspire the government to fight climate change and stop future crises!"
							]
]

global.npc_counters = [0, 0]
font = MainFont
text_color = c_black;
padding = 80;
width = 150;
height = 150;
font = MsgFont;
